# Generated by Django 5.1.7 on 2025-03-23 03:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crime_type', models.CharField(choices=[('theft', 'theft'), ('assault', 'assault'), ('vandalism', 'vandalism'), ('fraud', 'fraud'), ('embezzlement', 'embezzlement'), ('forgery', 'forgery'), ('identity_fraud', 'identity fraud'), ('defamation', 'defamation'), ('libel', 'libel'), ('slander', 'slander'), ('trespassing', 'trespassing'), ('identity_theft', 'identity theft'), ('counterfeiting', 'counterfeiting'), ('copyright_infringement', 'copyright infringement'), ('smuggling', 'smuggling'), ('tax_evasion', 'tax evasion'), ('illegal_gambling', 'illegal gambling'), ('bribery_passive', 'bribery (passive)'), ('bribery_active', 'bribery (active)'), ('unlawful_sale_of_goods', 'unlawful sale of goods'), ('money_laundering', 'money laundering'), ('environmental_violation', 'environmental violation')], max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('reported_by', models.CharField(max_length=100)),
                ('precinct', models.CharField(blank=True, max_length=10, null=True)),
                ('admin_district', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Crimes',
            },
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('arrest_status', models.BooleanField(default=False)),
                ('last_known_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Criminals',
            },
        ),
        migrations.CreateModel(
            name='CriminalOffense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offense_date', models.DateTimeField()),
                ('sentence_status', models.CharField(choices=[('under_investigation', 'Under Investigation'), ('charged', 'Charged'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted')], default='under_investigation', max_length=50)),
                ('crime_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crimeincident')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criminal')),
            ],
            options={
                'verbose_name_plural': 'Offenses',
                'unique_together': {('criminal', 'crime_incident')},
            },
        ),
    ]
