# Generated by Django 5.1.7 on 2025-03-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaloffense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='criminaloffense',
            name='process_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='criminaloffense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
