# Generated by Django 5.1.7 on 2025-03-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnerCompany',
            new_name='CrimeIncident',
        ),
    ]
