# Generated by Django 5.1.7 on 2025-03-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_criminaloffense_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaloffense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='criminaloffense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
