# Generated by Django 5.1.7 on 2025-03-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_criminaloffense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimeincident',
            name='criminals',
            field=models.ManyToManyField(blank=True, related_name='crimes', to='core.criminal'),
        ),
    ]
