# Generated by Django 5.1.7 on 2025-03-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_crimeincident_criminals'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=255)),
                ('crime_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CrimeStatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=255)),
                ('crime_count', models.IntegerField()),
                ('crime_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_sentence_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recidivism_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=255)),
                ('trend_date', models.DateField()),
                ('trend_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField()),
                ('stat_value', models.IntegerField()),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_stats', to='core.crimeincident')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_stats', to='core.criminal')),
                ('offense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_stats', to='core.criminaloffense')),
            ],
        ),
    ]
