# Generated by Django 5.1.7 on 2025-03-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimestats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimeheatmap',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
